### ISSUE TITLE
Question: Excluding some Collections from Overlay

### ISSUE THREAD

**Issue by rjwinks** [gssariev/maintainerr-overlay-helperr#1]
Just wanted to ask if it's possible to exclude certain collections in maintainerr from getting the overlay applied through this script/container?

**Comment by gssariev** [comment]
> Just wanted to ask if it's possible to exclude certain collections in maintainerr from getting the overlay applied through this script/container?

Apologies for the late reply. I am working on implementing this as the script will currently apply an overlay to all collections. Keep an eye our for a new release (hopefully in a day or two from posting this)

**Comment by gssariev** [comment]
> Just wanted to ask if it's possible to exclude certain collections in maintainerr from getting the overlay applied through this script/container?

Following up on my last comment - you can test the 'develop' build of the script as it includes the option to select which collections you want the overlay applied to.

- Use this image: `gsariev/maintainerr-overlay-helperr:develop`
- Add the following line your docker-compose: `SELECTED_COLLECTION_IDS: <id>,<id>,<id>` (add ids separated by comma)

You can get the ids of your collections at `http://YOUR_MAINTANERR_ADDRESS:PORT/api/collections`. Look for the `id` value for the collection you want to use.

Let me know how it goes :)

**Comment by rjwinks** [comment]
awesome! I'll give it a shot and let you know

Thanks so much!

**Comment by gssariev** [comment]
> awesome! I'll give it a shot and let you know
> 
> Thanks so much!

Just a heads up, as I saw that I made a mistake in my comment above - look for value of `collectionId` .
